stages:
  - build
  - deploy

javalint:
  stage: build
  tags:
    - wsbank
  script:
    - 'mvn $MAVEN_CLI_OPTS package'

deploy_to_aws:
  stage: deploy
  tags:
    - wsbank
  before_script:
   # Generates to connect to the AWS unit the SSH key.
   - mkdir -p ~/.ssh
   - echo -e “$SSH_PRIVATE_KEY” > ~/.ssh/tubes2wbd.pem
   # Sets the permission to 600 to prevent a problem with AWS
   # that it’s too unprotected.
   - chmod 600 ~/.ssh/tubes2wbd.pem
   - bash .ignore-host-check.sh
  script:
    - bash .gitlab-deploy.aws.sh
  environment:
    name: production
    url: ec2-54-89-199-114.compute-1.amazonaws.com
