version: "3.6"
services:
  wsbank-database:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:5.7.28
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
  wsbank-tomcat:
    container_name: ${TOMCAT_CONTAINER_NAME}
    build: ./
    ports:
      - ${TOMCAT_HOST_PORT}:8080
    env_file:
      - ./.env
    volumes:
      - ./src/main/java/com/webservice/database/Database.java:/usr/local/tomcat/Database.java